core/urls.py
from django.conf.urls.defaults import patterns, url

from core import views

urlpatterns = patterns("",

    url(regex=r'^$',
        view=views.DashboardView.as_view(),
        name='dashboard'),

)

profiles/urls.py
from django.conf.urls.defaults import patterns, url

from profiletools import views

from profiles.views import ProfileUpdateView

urlpatterns = patterns("",
    url(regex=r'^$',
        view=views.LoginRequireProfileListView.as_view(),
        name='profile_list'),
    url(regex=r'^mine/$',
        view=ProfileUpdateView.as_view(),
        name='profile_update'),
    url(regex=r'^(?P<pk>\d+)/$',
        view=views.ProfileDetailView.as_view(),
        name='profile_detail'),
)

proj/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView

admin.autodiscover()


urlpatterns = patterns('',

    url(regex=r'^$',
        view=TemplateView.as_view(template_name="home.html"),
        name="home"
        ),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dashboard/', include('core.urls')),
    #url(r'^protocols/', include('protocols.urls')),
    url(r'^profiles/', include('profiles.urls')),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'registration/login.html'}, name="login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', {'login_url': '/login/'}, 'logout',),
)


if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

core/models.py
from django.db import models

# Create your models here.

profiles/models.py
from django.contrib.auth.models import User
from django.contrib.localflavor.us.models import USStateField
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _

from django_extensions.db.models import TimeStampedModel


class Profile(TimeStampedModel):

    user = models.OneToOneField(User)
    first_name = models.CharField(_("First Name"), max_length="30", null=True, blank=True)
    last_name = models.CharField(_("Last Name"), max_length="30", null=True, blank=True)
    mobile = models.CharField(_("Mobile"), max_length="15", null=True, blank=True)
    address_1 = models.CharField(_("Address 1"), max_length=100, null=True, blank=True)
    address_2 = models.CharField(_("Address 2"), max_length=100, null=True, blank=True)
    city = models.CharField(_("City"), max_length=100, null=True, blank=True)
    state = USStateField(_("State"), null=True, blank=True)
    zip_code = models.CharField(_("Zip Code"), max_length=10, null=True, blank=True)

    def __unicode__(self):
        if self.first_name or self.last_name:
            return "{0} {1}".format(self.first_name, self.last_name)
        user = self.user

        return user.username

    def get_absolute_url(self):

        return reverse("profile_detail", kwargs={"pk": self.pk})

profiles/forms.py
from django import forms

from profiles.models import Profile


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        exclude = ('user', 'is_staff', 'is_admin',)

core/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView

from braces.views import LoginRequiredMixin

from core.utils import check_protocol_edit_authorization
#from protocols.models import Protocol


class DashboardView(LoginRequiredMixin, TemplateView):

    template_name = "core/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        return context

"""
class AuthorizedForProtocolMixin(object):

    def get_protocol(self):
        if hasattr(self, "protocol"):
            return self.protocol
        slug = self.kwargs.get('protocol_slug', None)
        if slug is None:
            raise Http404()

        # Is there an object attached to self?
        if hasattr(self, "object"):
            # If so, and it's a Protocol, then use that
            if isinstance(self.object, Protocol):
                protocol = self.object
            else:
                # Otherwise find the protocol normally
                protocol = get_object_or_404(Protocol, slug=self.kwargs.get('protocol_slug', None))
        else:
            # Find the protocol normall
            protocol = get_object_or_404(Protocol, slug=self.kwargs.get('protocol_slug', None))

        # If superuser, staff, or owner show it
        if self.request.user.is_authenticated:
            if check_protocol_edit_authorization(protocol, self.request.user):
                return protocol

        # if published just show it.
        if protocol.status == protocol.STATUS_PUBLISHED:
            return protocol

        # unpublished and not authenticated or part of the org that owns it.
        raise Http404()

    def get_context_data(self, **kwargs):
        self.protocol = self.get_protocol()
        context = super(AuthorizedForProtocolMixin, self).get_context_data(**kwargs)
        context['protocol'] = self.protocol
        context['protocol_edit_authorization'] = check_protocol_edit_authorization(self.protocol, self.request.user)
        return context


class AuthorizedforProtocolEditMixin(object):

    def check_authorization(self):
        if not check_protocol_edit_authorization(self.protocol, self.request.user):
            raise Http404

    def get_context_data(self, **kwargs):
        self.check_authorization()
        return super(AuthorizedforProtocolEditMixin, self).get_context_data(**kwargs)
"""

profiles/views.py
from django.views.generic import UpdateView

from braces.views import LoginRequiredMixin

from profiles.forms import ProfileForm
from profiles.models import Profile


class ProfileUpdateView(LoginRequiredMixin, UpdateView):

    model = Profile
    form_class = ProfileForm

    def get_object(self):
        profile, created = Profile.objects.get_or_create(
            user=self.request.user
        )
        return profile

proj/templates/_base.html
<html>
<head>

    <title>Proj: {% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/style.css">
    {% block extracss %}{% endblock %}
    
</head>


<body>
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
        <ul class="nav">
          <li class="active">
            {% if request.user.is_authenticated %}            
              <a href="{% url dashboard %}"><i class="icon-home icon-white"></i> Home</a>
            {% else %}
              <a href="{% url home %}"><i class="icon-home icon-white"></i> Home</a>
            {% endif %}
          </li>
        </ul>
        {% if request.user.is_authenticated %}
          <ul class="nav pull-right">
              {% if request.my_profile == None %}
                  <li class="active"><a>{{ request.user }}</a></li>
              {% else %}
                  <li class="active"><a href="{% url profile_detail request.my_profile.pk %}">{{ request.user }}</a></li>
              {% endif %}
            <li><a href="{% url logout %}">logout</a></li>  
          </ul>
        {% else %}
            <ul class="nav pull-right">
                <li><a href="{% url registration_register %}">Register</a></li>
              <li><a href="{% url login %}">Login</a></li>  
            </ul>        
        {% endif %}

    </div>
  </div>
</div>  
<div class="container-fluid">

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success">
                <a class="close">×</a>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <!-- breadcrumps -->
    {% if breadcrumbs %}
      <div class="row">
        <div class="span12">
            <ul class="breadcrumb">
              {% for breadcrumb in breadcrumbs %}
                <li {% if forloop.last %}class="active"{% endif %}><a href="{{ breadcrumb.0 }}">{{ breadcrumb.1 }}</a> {% if not forloop.last %}<span class="divider">/</span>{% endif %}</li>
              {% endfor %}
            </ul>
      </div>
    </div>
    {% endif %}

    <!-- page title -->
    <div class="row">
      <div class="span12">
      <div class="page-header">
        <h1>{% block page_title %}{% endblock %}</h1>
      </div>
    </div>
  </div>
  <!-- page content -->
{% block content %}{% endblock %}      
</div>

<script src="{{ STATIC_URL }}js/jquery-1.8.0.min.js"></script>    
<script src="{{ STATIC_URL }}js/bootstrap.min.js" type="text/javascript"></script>

{% block extrajs %}
{% endblock %}


</body>
</html>

proj/templates/_base_hero.html
<html>
<head>

    <title>Proj: {% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/custom.css">
    {% block extracss %}{% endblock %}
    
</head>


<body>
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
        <ul class="nav">
          <li class="active">
            {% if request.user.is_authenticated %}            
              <a href="{% url dashboard %}"><i class="icon-home icon-white"></i> Home</a>
            {% else %}
              <a href="{% url home %}"><i class="icon-home icon-white"></i> Home</a>
            {% endif %}
          </li>
        </ul>
        {% if request.user.is_authenticated %}
          <ul class="nav pull-right">
              <li class="active"><a>{{ request.user }}</a></li>
            <li><a href="{% url logout %}">logout</a></li>  
          </ul>
        {% else %}
            <ul class="nav pull-right">
                <li><a href="{% url registration_register %}">Register</a></li>
              <li><a href="{% url login %}">Login</a></li>  
            </ul>        
        {% endif %}

    </div>
  </div>
</div>  
<div class="container-fluid">

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success">
                <a class="close">×</a>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

  <!-- page content -->
{% block content %}{% endblock %}      
</div>

<script src="{{ STATIC_URL }}js/jquery-1.8.0.min.js"></script>    
<script src="{{ STATIC_URL }}js/bootstrap.min.js" type="text/javascript"></script>

{% block extrajs %}
{% endblock %}


</body>
</html>

proj/templates/core/dashboard.html
{% extends "_base.html" %}
{% load core_tags %}

{% block title %}Dashboard{% endblock %}

{% block page_title %}Dashboard{% endblock %}

{% block content %}
<div class="row">
    <div class="span12">
        <ul>
            <li><a href="{% url profile_list %}">Users</a></li>
        </ul>

    </div>
  </div>
{% endblock %}

proj/templates/core/model_instance_data_table.html
<table class="table table-striped">
    <thead>
        <tr>
            <th>Attribute</th>
            <th>Value</th>        
        </tr>
    </thead>
    <tbody>
        {% for field in fields %}
            <tr>
                <td>{{ field.key }}</td>
                <td>{{ field.value }}</td>                
            </tr>
        {% endfor %}
    </tbody>
</table>

proj/templates/home.html
{% extends "_base_hero.html" %}

{% block title %}{% endblock %}

{% block content %}
  
  <div class="row">
    <div class="span12">
    <div class="hero-unit">
      <h1>Proj</h1>
      <p>Because we do research right</p>
      <p>
        <a class="btn btn-primary btn-large">
          Learn more
        </a>
        
      </p>
    </div>
    </div>
  </div>
{% endblock %}

proj/templates/profiles/profile_detail.html
{% extends "_base.html" %}
{% load core_tags %}

{% block title %}Profile: {{ object }}{% endblock %}

{% block page_title %}<a href="{% url profile_list %}">Profile</a>: {{ object }}
{% if protocol_edit_authorization %} 
    <small><a href="{% url profile_update %}"><i class="icon-edit"></i></a></small>
{% endif %}
{% endblock %}

{% block content %}

<div class="row">
    <div class="span6">
        <h2>Detail</h2>
        {% object_data_table object %}
    </div>
  
  </div>
{% endblock %}

proj/templates/profiles/profile_form.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}

{% block title %}Profile{% if object %}: {{ object }}{% endif %}{% endblock %}

{% block page_title %}Profile{% if object %}: <a href="{{ object.get_absolute_url }}">{{ object }}</a>{% endif %}{% endblock %}

{% block content %}
<div class="row">

    <!-- main form div -->
    <div class="span6">
      <form action="." method="post" class="form-stacked well">{% csrf_token %}
      {{ form|crispy }}
        <div class="actions">
          <input type="submit" class="btn btn-primary" value="Submit">
        </div>
      </form>
    </div>

  </div>
{% endblock %}

{% block extrajs %}
<script>
    $(document).ready(function(){
        $("#id_first_name").focus();
    });
</script>
{% endblock extrajs %}

proj/templates/profiles/profile_list.html
{% extends "_base.html" %}

{% block title %}Profile List{% endblock %}

{% block page_title %}Profile List {% endblock %}

{% block content %}
<div class="row">
    <div class="span12">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Joined</th>
                </tr>
            </thead>
            <tbody>
                {% for profile in object_list %}
                    <tr>
                        <td><a href="{{ profile.get_absolute_url }}">{{ profile }}</a></td>
                        <td>{{ profile.created }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
  </div>
{% endblock %}